// <auto-generated />
namespace MusicProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullArtist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullArtist));
        
        string IMigrationMetadata.Id
        {
            get { return "201602252222517_nullArtist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
